name: CICD pipeline making
on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Read the file
        run: cat README.md
      - name: Read Hello file
        run: cat Hello.txt

      